<?php

/*
 * Branding configs for your application
 */
return [
    'login' => [
        'page_title' => 'Connexion',
        'headline' => 'Connexion',
        'subheadline' => 'Connecte toi au dessous !',
        'show_subheadline' => false,
        'email_address' => 'Adresse mail',
        'password' => 'Mot de passe',
        'remember_me' => 'Se Souvenir de moi',
        'edit' => 'Modifier',
        'button' => 'Continuer',
        'forget_password' => 'Mot de passe oublié ?',
        'dont_have_an_account' => 'Pas encore de compte ?',
        'sign_up' => "S'inscrire",
        'social_auth_authenticated_message' => "Vous vous êtes connecté via __social_providers_list__. S'il te plait connecte toi avec ce réseau au dessus..",
        'change_email' => "Changer d'email",
        'couldnt_find_your_account' => 'Compte introuvable',
    ],
    'register' => [
        'page_title' => "S'inscrire",
        'headline' => "S'inscrire",
        'subheadline' => 'Creer ton compte gratuitement au dessous !',
        'show_subheadline' => false,
        'name' => 'Nom',
        'email_address' => 'Adresse mail',
        'password' => 'Mot de passe',
        'password_confirmation' => 'Confirmation du mot de passe',
        'already_have_an_account' => 'Vous avez déjà un compte ?',
        'sign_in' => 'Connexion',
        'button' => 'Continuer',
    ],
    'verify' => [
        'page_title' => 'Verifie ton compte',
        'headline' => 'Verifie ton compte',
        'subheadline' => 'Avant de pouvoir continuer, tu dois vérifier votre adresse mail.',
        'show_subheadline' => false,
        'description' => "Avant de poursuivre, vérifie ton mail pour obtenir un lien de vérification. Si tu n'as pas reçu le mail,",
        'new_request_link' => 'cliquez ici pour en demander un autre',
        'new_link_sent' => 'Un nouveau lien a été envoyé à votre adresse mail.',
        'or' => 'Ou',
        'logout' => 'cliquez ici pour te déconnecter',
    ],
    'passwordConfirm' => [
        'page_title' => 'Confirme ton mot de passe',
        'headline' => 'Confirme ton mot de passe',
        'subheadline' => 'Assure toi de confirmer votre mot de passe ci-dessous',
        'show_subheadline' => false,
        'password' => 'Mot de passe',
        'button' => 'Mot de passe',
    ],
    'passwordResetRequest' => [
        'page_title' => 'Demander une réinitialisation du mot de passe',
        'headline' => 'Réinitialiser mot de passe',
        'subheadline' => 'Entre ton adresse mail ci-dessous pour réinitialiser ton mot de passe',
        'show_subheadline' => false,
        'email' => 'Addresse mail ',
        'button' => 'Envoyer le lien de réinitialisation du mot de passe',
        'or' => 'ou',
        'return_to_login' => 'retour à la connexion',
    ],
    'passwordReset' => [
        'page_title' => 'Réinitialise ton mot de passe',
        'headline' => 'Réinitialiser mot de passe',
        'subheadline' => 'Réinitialise ton mot de passe ci-dessous',
        'show_subheadline' => false,
        'email' => 'Adresse mail ',
        'password' => 'Mot de passe',
        'password_confirm' => 'Confirmation du mot de passe',
        'button' => 'Réinitialiser mot de passe',
    ],
    'twoFactorChallenge' => [
        'page_title' => 'Two Factor Challenge',
        'headline_auth' => 'Authentication Code',
        'subheadline_auth' => 'Enter the authentication code provided by your authenticator application.',
        'show_subheadline_auth' => false,
        'headline_recovery' => 'Recovery Code',
        'subheadline_recovery' => 'Please confirm access to your account by entering one of your emergency recovery codes.',
        'show_subheadline_recovery' => false,
    ],

];
