name: tests

on: [push, pull_request]

jobs:
  pest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, sqlite, pcov
          coverage: pcov

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}

      - name: Install deps
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: App key + env
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        run: ./vendor/bin/pest --parallel --coverage
